import { Product } from './store'

// Product catalog - updated March 2026
export const products: Product[] = [
  // WOMEN'S PRODUCTS
  {
    id: 1,
    name: "Oversized Linen Blazer",
    brand: "ZARA",
    price: 129,
    originalPrice: 179,
    image: "https://images.unsplash.com/photo-1591369822096-ffd140ec948f?w=400&h=500&fit=crop",
    category: "Women",
    rating: 4.8,
    reviews: 324,
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Beige", "Black", "Navy"],
    description: "Elevate your wardrobe with this premium oversized linen blazer. Perfect for both casual and formal occasions.",
    isNew: true,
    isTrending: true
  },
  {
    id: 3,
    name: "Floral Maxi Dress",
    brand: "Mango",
    price: 89,
    image: "https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=400&h=500&fit=crop",
    category: "Women",
    rating: 4.7,
    reviews: 189,
    sizes: ["XS", "S", "M", "L"],
    colors: ["Blue Floral", "Pink Floral"],
    description: "Stunning floral maxi dress perfect for summer events and beach vacations.",
    isNew: true
  },
  {
    id: 5,
    name: "High-Waist Wide Leg Pants",
    brand: "COS",
    price: 99,
    originalPrice: 139,
    image: "https://images.unsplash.com/photo-1509631179647-0177331693ae?w=400&h=500&fit=crop",
    category: "Women",
    rating: 4.9,
    reviews: 256,
    sizes: ["XS", "S", "M", "L"],
    colors: ["Black", "Cream", "Brown"],
    description: "Sophisticated high-waist wide leg pants for a chic, elongated silhouette.",
    isNew: true,
    isTrending: true
  },
  {
    id: 7,
    name: "Silk Blend Blouse",
    brand: "Massimo Dutti",
    price: 79,
    originalPrice: 99,
    image: "https://images.unsplash.com/photo-1564257631407-4deb1f99d992?w=400&h=500&fit=crop",
    category: "Women",
    rating: 4.7,
    reviews: 145,
    sizes: ["XS", "S", "M", "L"],
    colors: ["Ivory", "Blush", "Black"],
    description: "Elegant silk blend blouse with delicate detailing for sophisticated styling.",
    isNew: true
  },
  {
    id: 9,
    name: "Pleated Midi Skirt",
    brand: "& Other Stories",
    price: 69,
    image: "https://images.unsplash.com/photo-1583496661160-fb5886a0afe3?w=400&h=500&fit=crop",
    category: "Women",
    rating: 4.6,
    reviews: 234,
    sizes: ["XS", "S", "M", "L"],
    colors: ["Black", "Navy", "Burgundy"],
    description: "Flowing pleated midi skirt that moves beautifully with every step."
  },
  {
    id: 11,
    name: "Cashmere Sweater",
    brand: "Everlane",
    price: 148,
    image: "https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=400&h=500&fit=crop",
    category: "Women",
    rating: 4.9,
    reviews: 312,
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Oatmeal", "Black", "Burgundy", "Forest Green"],
    description: "Luxuriously soft 100% cashmere sweater for ultimate comfort.",
    isNew: true
  },
  // MEN'S PRODUCTS
  {
    id: 2,
    name: "Slim Fit Chinos",
    brand: "H&M",
    price: 49,
    originalPrice: 69,
    image: "https://images.unsplash.com/photo-1552374196-1ab2a1c593e8?w=400&h=500&fit=crop",
    category: "Men",
    rating: 4.5,
    reviews: 512,
    sizes: ["28", "30", "32", "34", "36"],
    colors: ["Khaki", "Navy", "Olive"],
    description: "Classic slim fit chinos crafted from premium cotton blend for ultimate comfort.",
    isTrending: true
  },
  {
    id: 4,
    name: "Premium Cotton T-Shirt",
    brand: "Uniqlo",
    price: 29,
    image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400&h=500&fit=crop",
    category: "Men",
    rating: 4.6,
    reviews: 1024,
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["White", "Black", "Grey", "Navy"],
    description: "Essential premium cotton t-shirt with a comfortable regular fit.",
    isTrending: true
  },
  {
    id: 6,
    name: "Denim Jacket Classic",
    brand: "Levi's",
    price: 139,
    image: "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=400&h=500&fit=crop",
    category: "Men",
    rating: 4.8,
    reviews: 678,
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Light Blue", "Dark Blue", "Black"],
    description: "Timeless denim jacket that never goes out of style. A wardrobe essential."
  },
  {
    id: 8,
    name: "Wool Blend Overcoat",
    brand: "COS",
    price: 249,
    originalPrice: 329,
    image: "https://images.unsplash.com/photo-1617127365659-c47fa864d8bc?w=400&h=500&fit=crop",
    category: "Men",
    rating: 4.9,
    reviews: 89,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Camel", "Black", "Grey"],
    description: "Luxurious wool blend overcoat for cold weather elegance.",
    isTrending: true
  },
  {
    id: 12,
    name: "Tailored Suit Pants",
    brand: "Hugo Boss",
    price: 199,
    originalPrice: 259,
    image: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=400&h=500&fit=crop",
    category: "Men",
    rating: 4.7,
    reviews: 167,
    sizes: ["28", "30", "32", "34", "36", "38"],
    colors: ["Navy", "Charcoal", "Black"],
    description: "Impeccably tailored suit pants for the modern professional."
  },
  {
    id: 13,
    name: "Casual Polo Shirt",
    brand: "Ralph Lauren",
    price: 89,
    image: "https://images.unsplash.com/photo-1625910513413-5fc45b6c3ce2?w=400&h=500&fit=crop",
    category: "Men",
    rating: 4.6,
    reviews: 445,
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Navy", "White", "Red"],
    description: "Classic polo shirt with signature embroidered logo for timeless style.",
    isTrending: true
  },
  // FOOTWEAR PRODUCTS
  {
    id: 10,
    name: "Leather Chelsea Boots",
    brand: "Clarks",
    price: 179,
    originalPrice: 219,
    image: "https://images.unsplash.com/photo-1638247025967-b4e38f787b76?w=400&h=500&fit=crop",
    category: "Footwear",
    rating: 4.8,
    reviews: 456,
    sizes: ["6", "7", "8", "9", "10", "11", "12"],
    colors: ["Black", "Brown", "Tan"],
    description: "Premium leather Chelsea boots crafted for comfort and durability.",
    isTrending: true
  },
  {
    id: 14,
    name: "White Sneakers",
    brand: "Adidas",
    price: 99,
    originalPrice: 129,
    image: "https://images.unsplash.com/photo-1549298916-b41d501d3772?w=400&h=500&fit=crop",
    category: "Footwear",
    rating: 4.7,
    reviews: 892,
    sizes: ["6", "7", "8", "9", "10", "11", "12"],
    colors: ["White", "Black", "Grey"],
    description: "Clean and minimal white sneakers perfect for everyday wear.",
    isNew: true,
    isTrending: true
  },
  {
    id: 15,
    name: "Running Shoes",
    brand: "Nike",
    price: 149,
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&h=500&fit=crop",
    category: "Footwear",
    rating: 4.9,
    reviews: 1256,
    sizes: ["6", "7", "8", "9", "10", "11", "12"],
    colors: ["Red", "Black", "Blue"],
    description: "High-performance running shoes with responsive cushioning.",
    isNew: true
  },
  {
    id: 16,
    name: "Women's Heeled Sandals",
    brand: "Steve Madden",
    price: 89,
    originalPrice: 119,
    image: "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=400&h=500&fit=crop",
    category: "Footwear",
    rating: 4.5,
    reviews: 234,
    sizes: ["5", "6", "7", "8", "9", "10"],
    colors: ["Nude", "Black", "Gold"],
    description: "Elegant heeled sandals perfect for special occasions.",
    isTrending: true
  },
  {
    id: 17,
    name: "Leather Loafers",
    brand: "Cole Haan",
    price: 159,
    image: "https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?w=400&h=500&fit=crop",
    category: "Footwear",
    rating: 4.8,
    reviews: 345,
    sizes: ["7", "8", "9", "10", "11", "12"],
    colors: ["Brown", "Black", "Burgundy"],
    description: "Classic leather loafers with cushioned footbed for all-day comfort."
  },
  {
    id: 18,
    name: "Canvas Slip-Ons",
    brand: "Vans",
    price: 55,
    image: "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=400&h=500&fit=crop",
    category: "Footwear",
    rating: 4.6,
    reviews: 678,
    sizes: ["6", "7", "8", "9", "10", "11", "12"],
    colors: ["Black", "White", "Checkered"],
    description: "Iconic slip-on sneakers for effortless casual style.",
    isNew: true
  },
  // ACCESSORIES PRODUCTS
  {
    id: 19,
    name: "Leather Crossbody Bag",
    brand: "Coach",
    price: 195,
    originalPrice: 250,
    image: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=400&h=500&fit=crop",
    category: "Accessories",
    rating: 4.8,
    reviews: 567,
    sizes: ["One Size"],
    colors: ["Brown", "Black", "Tan"],
    description: "Elegant leather crossbody bag with adjustable strap and multiple compartments.",
    isTrending: true
  },
  {
    id: 20,
    name: "Classic Aviator Sunglasses",
    brand: "Ray-Ban",
    price: 159,
    image: "https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=400&h=500&fit=crop",
    category: "Accessories",
    rating: 4.9,
    reviews: 1234,
    sizes: ["One Size"],
    colors: ["Gold/Green", "Silver/Blue", "Black/Grey"],
    description: "Iconic aviator sunglasses with polarized lenses and UV protection.",
    isNew: true
  },
  {
    id: 21,
    name: "Silk Scarf",
    brand: "Hermès",
    price: 89,
    originalPrice: 120,
    image: "https://images.unsplash.com/photo-1601370690183-1c7796ecec61?w=400&h=500&fit=crop",
    category: "Accessories",
    rating: 4.7,
    reviews: 234,
    sizes: ["One Size"],
    colors: ["Multi", "Blue", "Red"],
    description: "Luxurious silk scarf with elegant printed pattern.",
    isTrending: true
  },
  {
    id: 22,
    name: "Leather Belt",
    brand: "Gucci",
    price: 75,
    image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&h=500&fit=crop",
    category: "Accessories",
    rating: 4.6,
    reviews: 456,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Brown", "Black"],
    description: "Premium leather belt with classic buckle design."
  },
  {
    id: 23,
    name: "Minimalist Watch",
    brand: "Daniel Wellington",
    price: 179,
    originalPrice: 229,
    image: "https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=400&h=500&fit=crop",
    category: "Accessories",
    rating: 4.8,
    reviews: 890,
    sizes: ["One Size"],
    colors: ["Rose Gold", "Silver", "Gold"],
    description: "Elegant minimalist watch with interchangeable straps.",
    isNew: true,
    isTrending: true
  },
  {
    id: 24,
    name: "Canvas Tote Bag",
    brand: "Madewell",
    price: 68,
    image: "https://images.unsplash.com/photo-1544816155-12df9643f363?w=400&h=500&fit=crop",
    category: "Accessories",
    rating: 4.5,
    reviews: 345,
    sizes: ["One Size"],
    colors: ["Natural", "Black", "Navy"],
    description: "Spacious canvas tote perfect for everyday use."
  },
  // ACTIVEWEAR PRODUCTS
  {
    id: 25,
    name: "High-Waist Yoga Leggings",
    brand: "Lululemon",
    price: 98,
    image: "https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=400&h=500&fit=crop",
    category: "Activewear",
    rating: 4.9,
    reviews: 2345,
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "Navy", "Burgundy"],
    description: "Buttery-soft high-waist leggings with four-way stretch.",
    isTrending: true
  },
  {
    id: 26,
    name: "Performance Running Shorts",
    brand: "Nike",
    price: 55,
    originalPrice: 70,
    image: "https://images.unsplash.com/photo-1591195853828-11db59a44f6b?w=400&h=500&fit=crop",
    category: "Activewear",
    rating: 4.7,
    reviews: 876,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "Grey", "Blue"],
    description: "Lightweight running shorts with built-in liner and zip pocket.",
    isNew: true
  },
  {
    id: 27,
    name: "Sports Bra",
    brand: "Under Armour",
    price: 45,
    image: "https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=400&h=500&fit=crop",
    category: "Activewear",
    rating: 4.8,
    reviews: 567,
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "White", "Pink"],
    description: "High-support sports bra with moisture-wicking fabric.",
    isTrending: true
  },
  {
    id: 28,
    name: "Training Tank Top",
    brand: "Adidas",
    price: 35,
    image: "https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=400&h=500&fit=crop",
    category: "Activewear",
    rating: 4.6,
    reviews: 432,
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["White", "Black", "Grey"],
    description: "Breathable training tank with ClimaCool technology."
  },
  {
    id: 29,
    name: "Zip-Up Hoodie",
    brand: "Gymshark",
    price: 65,
    originalPrice: 85,
    image: "https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=400&h=500&fit=crop",
    category: "Activewear",
    rating: 4.7,
    reviews: 654,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Grey", "Black", "Navy"],
    description: "Soft cotton-blend zip hoodie perfect for warm-ups.",
    isNew: true
  },
  {
    id: 30,
    name: "Compression Tights",
    brand: "2XU",
    price: 79,
    image: "https://images.unsplash.com/photo-1517438476312-10d79c077509?w=400&h=500&fit=crop",
    category: "Activewear",
    rating: 4.8,
    reviews: 321,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "Navy"],
    description: "Premium compression tights for enhanced performance and recovery.",
    isTrending: true
  }
]

export const categories = [
  { name: "Women", icon: "👗", count: 1240 },
  { name: "Men", icon: "👔", count: 890 },
  { name: "Footwear", icon: "👟", count: 456 },
  { name: "Accessories", icon: "👜", count: 678 },
  { name: "Activewear", icon: "🏃", count: 345 }
]

export const banners = [
  {
    id: 1,
    title: "Spring Collection",
    subtitle: "Up to 50% Off",
    image: "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=800&h=400&fit=crop",
    cta: "Shop Now"
  },
  {
    id: 2,
    title: "New Arrivals",
    subtitle: "Fresh Styles Just Landed",
    image: "https://images.unsplash.com/photo-1441984904996-e0b6ba687e04?w=800&h=400&fit=crop",
    cta: "Explore"
  }
]
